---
title: "02-exploratory-data-analysis"
output: 
  html_document:
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load data

```{r}
library(tidyverse)
data <- diamonds # TODO(alee) use iris for now
```


# "Shape" of the data

```{r}
str(data)
```


```{r}
summary(data)
```

```{r}
dim(data)
```


# Type of each variable

```{r}
library(tidyverse)
as_tibble(data)
```


# Preprocessing




# Count the number of data within each factor

```{r}
# find all the columns that are non numeric
col_non_numeric <- map(data, class) %>% 
  keep(function(x) any(x %in% c("factor", "character"))) %>% 
  names()
```

```{r}
col_non_numeric %>% 
  map(
    ~count(data, !!rlang::sym(.))
  )
```

# Distributions for numeric variables.

```{r}
col_numeric <- map(data, class) %>% 
  keep(function(x) any(x %in% c("numeric", "integer"))) %>% 
  names() 

col_numeric %>% 
  map(
    function(x) { 
      data %>% 
      ggplot(aes_string(x=x)) + 
      geom_histogram() + 
      labs(title=x) + 
      theme_bw()
    }
  )
```



```{r}

for(col in col_non_numeric) {
  print(col_numeric %>% 
    map(
      function(x) { 
        data %>% 
        ggplot(aes_string(x=x)) + 
        geom_histogram() + 
        labs(title=x) + 
        facet_grid(as.formula(paste0(col, " ~ ."))) + 
        theme_bw()
      }
    ))
  
}

```

